severity:
  "1": |-
    1無し：影響に気がつかない。 納入先での作業又は
    作業者に軽微な影響又は影響なし。
  "2": |-
    2かなり軽微：不具合について25%以下のユーザがクレームをつける。
    納入先ライン上で手直しを要すが廃却には至らない。
  "3": |-
    3軽微：不具合について50%以上のユーザがクレームをつける。
     納入先で選別を要すが廃却には至らない。
  "4": |-
    4かなり低い：不具合について75%以下のユーザがクレームをつける。
     納入先ラインサイドで手直しを要すが廃却には至らない。部分的に手直しを要す。
  "5": |-
    5低い：車両又は車両一部機能は作動するが、快適性、利便性の機能が低下する。
    一部のﾕｰｻﾞｰから苦情が出る。製品の100%手直しを要す。
  "6": |-
    6普通：製品の重要な機能、性能又は構造の喪失又は欠陥となる
    又はその恐れがある。製品の選別は必要ないが、製品の一部が廃却となる
  "7": |-
    7大：製品の重要な機能、性能又は構造の喪失又は欠陥となる。
    重大事故を引き起こす恐れがある。製品は全数選別を要し部分的に廃却になる。
  "8": |-
    8極めて大：製品の重要な機能、性能又は構造の喪失又は欠陥となる。
    重大事故を引き起こす。製品の100%が廃却となる。　ｻｰﾋﾞｽｷｬﾝﾍﾟｰﾝとなる。
  "9": |-
    9兆候を伴い車両の安全性に影響を与える。政府の規制に不適合になる。
    納入先での設備又は作業者が危険にさらされる。リコール、改善対策となる。
  "10": |-
    10兆候無しで車両の安全性に影響を与える。政府の規制に不適合になる。
    納入先での設備又は作業者が危険にさらされる。リコール、改善対策となる。
occurrence:
  "1": "1ほとんどない （Cpk=1.67以上、P＜0.00006％）"
  "2": "2低い、僅かに発生 P≧0.0006%"
  "3": "3低い、僅かに発生 P≧0.001%"
  "4": "4並、時々発生 P≧0.0１%"
  "5": "5並、時々発生 P≧0.05%"
  "6": "6並、時々発生 P≧0.2%"
  "7": "7高い、頻発発生 P≧１％"
  "8": "8高い、頻発発生 P≧２％"
  "9": "9非常に高い、継続発生 P≧5%"
  "10": "10非常に高い、継続発生 （Cpk<0.6、P≧7%）"
detection:
  "1": |-
    1気を配らなくても工程内で容易に検出できる。QA機器等により
    全数検査され、故障モードが自動的に検出され除去される。
  "2": |-
    2工程内で検出できる。QA機器等により全数検査され故障
    ﾓｰﾄﾞが自動的に検出される。
  "3": "3次工程で検出できる。 現行の工程管理方法で検出できる。"
  "4": "4生産ライン内で検出できる。 完成検査前の工程内の全数検査で検出できる。"
  "5": |-
    5完成検査による全数検査で検出できる。
    現行の工程管理方法で検出できる可能性がある。
  "6": |-
    6日常的な抜き取り検査で検出できる。
    現行の工程管理方法では見過ごされる可能性がある。
  "7": |-
    7現行の工程管理方法では検出は困難である。
    定期的な抜き取り検査で検出できる。
  "8": |-
    8出荷までに検出する事は極めて困難である。
     現行の工程管理方法では検出は極めて困難である。
  "9": "9検出の可能性はほぼ無し。"
  "10": "10ノーチェック。 検出できない。ほとんど不可能。"
