tenant_id: 6307204b

data:
  file_path: data/6307204b/preprocessed_stage4.csv
  preprocessed: true

elasticsearch:
  index: 6307204b_aqos
  mapping_file: drassist/spec/elasticsearch/defects.json 

search:
  fields:
    - "title"
    - "content"
    - "cause"
    - "countermeasure" 
    - "recurrence_prevention"

unit_list:
  - ブーム装置
  - ジブ伸縮機構（テレスコープ）
  - ジブ取付・格納機構
  - ジブ角度・チルト機構
  - ラフィングジブ
  - シングルトップジブ
  - ブーム起伏装置
  - 折曲装置
  - 旋回装置
  - ウインチ装置
  - フック装置
  - アウトリガ装置
  - カウンタウエイト装置
  - キャブ装置
  - コックピット制御システム
  - 外装装置
  - 昇降経路
  - フレーム
  - 走行装置
  - ドライブトレイン
  - 舵取装置
  - 制動装置
  - 緩衝装置
  - エンジン系
  - 上部パワートレーン（ePTO）
  - 油圧装置
  - 空圧装置
  - 電装／電送装置
  - 充電装置
  - 照明装置
  - 空調装置
  - 過負荷防止装置（AML）
  - 動作規制装置（AMC）
  - 範囲規制装置（AWL）
  - 巻過防止・インタロック類
  - アタッチメント装置
  - バケット装置
  - レベリング装置
  - リフト装置
  - ラジコン・リモコン装置
  - コンクリート圧送装置
  - 塗装全般
  - 銘板装置
  - 低騒音装置
  - 牽引装置
  - アシストカー
  - パッケージ装置
  - その他オプション

normalized_notation_dict:
  # カタカナ表記の統一
  アウタ:
    - アウター
  インナ:
    - インナー
  シリンダ:
    - シリンダー
  ストッパ:
    - ストッパー
  ワイヤ:
    - ワイヤー
  ローラ:
    - ローラー
  ベアリング:
    - ベア
  バッテリ:
    - バッテリー
  ウインチ:
    - ウィンチ
  ドレン:
    - ドレイン
    - ドレーン
  ラジエータ:
    - ラジエーター
    - ラジエター
  adblue:
    - アドブルー
  インタークーラ:
    - インタークーラー
  エアクリーナ:
    - エアクリーナー
    - エアークリーナ
  フィルタ:
    - フィルター
  エキゾースト:
    - エグゾースト
    - exh
    - e/x
  コネクタ:
    - コネクター
  マフラ:
    - マフラー
  ウォータセパレータ:
    - ウォーターセパレータ
  ウォータポンプ:
    - ウォーターポンプ
  リザーブタンク:
    - リザーバタンク
  フライホイール:
    - フライホィール
  ガバナ:
    - ガバナー
  スタータモータ:
    - スターターモーター
  ヒータ:
    - ヒーター
  エア:
    - エアー
  ウインドウウォッシャ:
    - ウインドウウォッシャー
    - ウインドウォッシャー
    - ウォッシャー
    - ウォッシャ
  パワーウインドウ:
    - パワーウィンド
    - パワーウィンドウ
  ワイパ:
    - ワイパー
  ウェザーストリップ:
    - ウェザストリップ
  アワメータ:
    - アワーメーター
  メータ:
    - メーター
  モータ:
    - モーター
  サイドバイザ:
    - サイドバイザー
  インジケータ:
    - インジケーター
  リア:
    - リヤ
  コンビネーションスイッチ:
    - コンビスイッチ
  シガーソケット:
    - シガレットソケット
  モニタ:
    - モニター
  アダプタ:
    - アダプター
  トランスミッタ:
    - トランスミッター
  リテーナ:
    - リテーナー
  スピーカ:
    - スピーカー
  ギヤ:
    - ギア
  バックラッシュ:
    - バックラッシ
  ポテンショメータ:
    - ポテンションメータ
  ロータリ:
    - ロータリー
  カプラ:
    - カプラー
  ボデー:
    - ボディ
  クリア:
    - クリアー
  ヤグラ:
    - やぐら
  カウンターウェイト:
    - c/w
    - cw
    - カウンタウエイト
  フェンダ:
    - フェンダー
  グリス:
    - グリース
  ウォーム:
    - ウオーム
  # 略語・アルファベット表記の統一
  アウトリガ:
    - o/r
    - or
  スイッチ:
    - s/w
    - sw
  ボックス:
    - box
  長さ検出器:
    - 長検
  エンジン:
    - e/g
    - eg
  scr:
    - scr
  アセンブリ:
    - assy
  ジブ:
    - jib
  トップ:
    - top
  ベース:
    - base
  リアゲート:
    - rゲート
  トルクコンバータ:
    - t/c
  トランスミッション:
    - t/m
  コンバータ:
    - コンバーター
  チャージャ:
    - チャージャー
  # 漢字・ひらがな・送り仮名の統一
  ガタ:
    - がた
  取付:
    - 取付け
  取出口:
    - 取出し口
  乱巻:
    - 乱巻き
  切換:
    - 切り換え
  引出し:
    - 引き出し
  吊環:
    - 吊り環
  手すり:
    - 手摺
    - 手摺り
  取っ手:
    - 取手
  割りピン:
    - 割ピン
  受台:
    - 受け台
  吊り上げ:
    - 吊上げ
  回り止め:
    - 廻り止め
  過巻:
    - 過巻き
    - 巻過
  あおり止め:
    - 煽り止め
  梯子掛け:
    - ハシゴ掛け
  合わせ:
    - 合せ
  βピン:
    - bピン
  車両:
    - 車輌
  泥除け:
    - 泥よけ
  取扱説明書:
    - 取説
  # 同義語・類義語の統一
  コントローラ:
    - 制御器
    - コントロールユニット
  操作ボックス:
    - オペレーションボックス
  # その他の統一
  チェックバルブ:
    - チェック弁
  リリーフバルブ:
    - リリーフ弁
  遮熱板:
    - 射熱板

model_numbers:
  rough_terrain_crane:
    - KR-002
    - KR-003
    - KR-004
    - KR-005
    - KR-006
    - KR-008
    - KR-014
    - KR-015
    - KR-018
    - KR-019
    - KR-021
    - KR-024
    - KR-026
    - KR-028
    - KR-029
    - KR-030
    - KR-031
    - KR-032
    - KR-034
    - KR-035
    - KR-037
    - KR-043
    - KR-045
    - KR-048
    - KR-049
    - KR-050
    - KR-051
    - KR-052
    - KR-053
    - KR-060
    - KR-062
    - KR-063
    - KR-064
    - KR-065
    - KR-067
    - KR-070
    - KR-071
    - KR-072
    - KR-073
    - KR-080
    - KR-082
    - KR-083
    - KR-084
    - KR-090
    - KR-091
    - KR-092
    - KR-094
    - KR-096
    - KR-097
    - KR-098
    - KR-099
    - KR-101
    - KR-104
    - KR-105
    - KR-106
    - KR-107
    - KR-111
    - KR-112
    - KR-113
    - KR-114
    - KR-119
    - KR-120
    - KR-121
    - KR-122
    - KR-123
    - KR-124
    - KR-125
    - KR-126
    - KR-128
    - KR-129
    - KR-130
    - KR-131
    - KR-132
    - KR-134
    - KR-139
    - KR-140
    - KR-141
    - KR-142
    - KR-143
    - KR-144
    - KR-145
    - KR-146
    - KR-148
    - KR-149
    - KR-150
    - KR-151
    - KR-152
    - KR-155
    - KR-157
    - KR-158
    - KR-159
    - KR-162
    - KR-163
    - KR-164
    - KR-165
    - KR-166
    - KR-167
    - KR-168
    - KR-169
    - KR-170
    - KR-172
    - KR-173
    - KR-174
    - KR-176
    - KR-179
    - KR-182
    - KR-183
    - eGR
    - GR
    - RK
    - TR
  aerial_work_platform:
    - KX
    - AT
    - AW
    - NUS
    - NUX